name: Manual Version Update

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Jenis update versi'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  manual-version-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Update version manually
      run: |
        python scripts/update_version.py --type ${{ github.event.inputs.version_type }}
    
    - name: Commit version changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app/build.gradle.kts VERSION_UPDATE.md
        git commit -m "🤖 Manual version update (${{ github.event.inputs.version_type }}) [skip ci]"
        git push
